export const FETCH_COUNTIES_LOADING = 'FETCH_COUNTIES_LOADING';
export const FETCH_COUNTIES_FULFILLED = 'FETCH_COUNTIES_FULFILLED';
export const FETCH_COUNTIES_REJECTED = 'FETCH_COUNTIES_REJECTED';
export const FETCH_COUNTY_DATA_LOADING = 'FETCH_COUNTY_DATA_LOADING';
export const FETCH_COUNTY_DATA_FULFILLED = 'FETCH_COUNTY_DATA_FULFILLED';
export const FETCH_COUNTY_DATA_REJECTED = 'FETCH_COUNTY_DATA_REJECTED';
